spring.application.name=upv-cal

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=1234

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# (Optional) Enable SQL logging for debugging
spring.jpa.show-sql=true